// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UMS.UI.Test.ERP.Areas.Student.Admission
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "StudentAdmission")]
    public partial class StudentAdmissionFeature : object, Xunit.IClassFixture<StudentAdmissionFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "StudentAdmission"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Areas/Student/Admission", "Student Admission", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "NewAdmission.feature"
#line hidden
        
        public StudentAdmissionFeature(StudentAdmissionFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="T1.0 New Student Admission Test")]
        [Xunit.TraitAttribute("FeatureTitle", "Student Admission")]
        [Xunit.TraitAttribute("Description", "T1.0 New Student Admission Test")]
        [Xunit.TraitAttribute("Category", "NewStudentAdmission")]
        [Xunit.TraitAttribute("Category", "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx")]
        [Xunit.TraitAttribute("Category", "DataSet:NewAdmission")]
        [Xunit.InlineDataAttribute("UDVASH", "", "", "", "Male", "Islam", "Admission", "82", "2024", "Bangla", "Mirpur Udvash", "Stadium Campus", "No", "Science", "1445, 1450", "", "2000", "2", "Branch Incharge", "4", "Special Discount", new string[0])]
        public async System.Threading.Tasks.Task T1_0NewStudentAdmissionTest(
                    string organization, 
                    string nickname, 
                    string regOrRoll, 
                    string mobile, 
                    string gender, 
                    string religion, 
                    string @class, 
                    string program, 
                    string session, 
                    string version, 
                    string branch, 
                    string campus, 
                    string timer, 
                    string group, 
                    string course, 
                    string received, 
                    string discount, 
                    string approvedBy, 
                    string discountType, 
                    string referredBy, 
                    string specialNote, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NewStudentAdmission",
                    "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx",
                    "DataSet:NewAdmission"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Organization", organization);
            argumentsOfScenario.Add("Nickname", nickname);
            argumentsOfScenario.Add("RegOrRoll", regOrRoll);
            argumentsOfScenario.Add("Mobile", mobile);
            argumentsOfScenario.Add("Gender", gender);
            argumentsOfScenario.Add("Religion", religion);
            argumentsOfScenario.Add("Class", @class);
            argumentsOfScenario.Add("Program", program);
            argumentsOfScenario.Add("Session", session);
            argumentsOfScenario.Add("Version", version);
            argumentsOfScenario.Add("Branch", branch);
            argumentsOfScenario.Add("Campus", campus);
            argumentsOfScenario.Add("Timer", timer);
            argumentsOfScenario.Add("Group", group);
            argumentsOfScenario.Add("Course", course);
            argumentsOfScenario.Add("Received", received);
            argumentsOfScenario.Add("Discount", discount);
            argumentsOfScenario.Add("ApprovedBy", approvedBy);
            argumentsOfScenario.Add("DiscountType", discountType);
            argumentsOfScenario.Add("ReferredBy", referredBy);
            argumentsOfScenario.Add("SpecialNote", specialNote);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("T1.0 New Student Admission Test", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
 await testRunner.GivenAsync("Navigate New Student Admission", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 15
  await testRunner.ThenAsync("Shown New Student Admission Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
  await testRunner.WhenAsync(string.Format("Enter The Student Nickname \"{0}\"", nickname), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
   await testRunner.AndAsync(string.Format("Enter The Student Mobile Number \"{0}\"", mobile), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
   await testRunner.AndAsync(string.Format("Select Student Gender \"{0}\"", gender), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
   await testRunner.AndAsync(string.Format("Select Student Religion \"{0}\"", religion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
   await testRunner.AndAsync(string.Format("Select Student Class \"{0}\" Type", @class), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
   await testRunner.AndAsync(string.Format("Select Student Program \"{0}\" Name", program), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
   await testRunner.AndAsync(string.Format("Select Session \"{0}\" Of Program", session), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
   await testRunner.AndAsync("Search Educational Institute Name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
   await testRunner.AndAsync(string.Format("Select Study Version \"{0}\" Type", version), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
   await testRunner.AndAsync(string.Format("Select Branch Name \"{0}\" Of Program", branch), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
   await testRunner.AndAsync(string.Format("Select Campus Name \"{0}\" Of Branch", campus), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
   await testRunner.AndAsync(string.Format("Click On Is Student Second Timer \"{0}\"", timer), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
   await testRunner.AndAsync(string.Format("Click On Student Academic Group \"{0}\"", group), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
   await testRunner.AndAsync(string.Format("Select Course Name \"{0}\" Of Program", course), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
  await testRunner.WhenAsync("Click On Admission Payment Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
  await testRunner.ThenAsync("Show Admission Payment Details Section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 38
  await testRunner.WhenAsync(string.Format("Enter Admission Received Amount \"{0}\"", received), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
  await testRunner.WhenAsync("Select Next Payment Receive Date", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
   await testRunner.AndAsync("Click On New Admission Submit Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
  await testRunner.ThenAsync("Shown Admitted Money Receipt Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
   await testRunner.AndAsync("Evaluate Admission Money Receipt Data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="T1.1 Old Admission In Complementary Course")]
        [Xunit.TraitAttribute("FeatureTitle", "Student Admission")]
        [Xunit.TraitAttribute("Description", "T1.1 Old Admission In Complementary Course")]
        [Xunit.TraitAttribute("Category", "ComplementaryOldStudentAdmission")]
        [Xunit.TraitAttribute("Category", "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx")]
        [Xunit.TraitAttribute("Category", "DataSet:Complementary")]
        [Xunit.InlineDataAttribute("UDVASH", "", "", "Male", "Islam", "Admission", "68", "2024", "Bangla", "Barishal Udvash", "Barishal Campus", "Online Campus", "Barishal Unmesh", " No", "Science", "1910", "Medical 2nd Time Special Course", "", "2000", "2", "Branch Incharge", "4", "Special Discount", new string[0])]
        public async System.Threading.Tasks.Task T1_1OldAdmissionInComplementaryCourse(
                    string organization, 
                    string regOrRoll, 
                    string mobile, 
                    string gender, 
                    string religion, 
                    string @class, 
                    string program, 
                    string session, 
                    string version, 
                    string branch, 
                    string campus, 
                    string campus2, 
                    string attachedBranch, 
                    string timer, 
                    string group, 
                    string course, 
                    string complementaryCourse, 
                    string received, 
                    string discount, 
                    string approvedBy, 
                    string discountType, 
                    string referredBy, 
                    string specialNote, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ComplementaryOldStudentAdmission",
                    "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx",
                    "DataSet:Complementary"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Organization", organization);
            argumentsOfScenario.Add("RegOrRoll", regOrRoll);
            argumentsOfScenario.Add("Mobile", mobile);
            argumentsOfScenario.Add("Gender", gender);
            argumentsOfScenario.Add("Religion", religion);
            argumentsOfScenario.Add("Class", @class);
            argumentsOfScenario.Add("Program", program);
            argumentsOfScenario.Add("Session", session);
            argumentsOfScenario.Add("Version", version);
            argumentsOfScenario.Add("Branch", branch);
            argumentsOfScenario.Add("Campus", campus);
            argumentsOfScenario.Add("Campus2", campus2);
            argumentsOfScenario.Add("AttachedBranch", attachedBranch);
            argumentsOfScenario.Add("Timer", timer);
            argumentsOfScenario.Add("Group", group);
            argumentsOfScenario.Add("Course", course);
            argumentsOfScenario.Add("ComplementaryCourse", complementaryCourse);
            argumentsOfScenario.Add("Received", received);
            argumentsOfScenario.Add("Discount", discount);
            argumentsOfScenario.Add("ApprovedBy", approvedBy);
            argumentsOfScenario.Add("DiscountType", discountType);
            argumentsOfScenario.Add("ReferredBy", referredBy);
            argumentsOfScenario.Add("SpecialNote", specialNote);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("T1.1 Old Admission In Complementary Course", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 48
 await testRunner.GivenAsync("Goto New Or Old Student Admission", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 49
  await testRunner.WhenAsync(string.Format("Enter Student RegOrRoll Number \"{0}\"", regOrRoll), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
   await testRunner.AndAsync("Navigate Old Student Admission", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
  await testRunner.ThenAsync("Shown Old Student Admission Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 52
  await testRunner.WhenAsync(string.Format("Enter The Student Mobile Number \"{0}\"", mobile), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
   await testRunner.AndAsync(string.Format("Select Student Class \"{0}\" Type", @class), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
   await testRunner.AndAsync(string.Format("Select Student Program \"{0}\" Name", program), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
   await testRunner.AndAsync(string.Format("Select Session \"{0}\" Of Program", session), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
   await testRunner.AndAsync("Search Educational Institute Name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
  await testRunner.WhenAsync(string.Format("Click On Complementary Course Name \"{0}\"", complementaryCourse), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
  await testRunner.WhenAsync("Click On Confirm Button In Modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 59
  await testRunner.ThenAsync("Is Show Complementary Course List", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 60
  await testRunner.WhenAsync(string.Format("Select Study Version \"{0}\" Type", version), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
   await testRunner.AndAsync(string.Format("Select Branch Name \"{0}\" Of Program", attachedBranch), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
   await testRunner.AndAsync(string.Format("Select Campus Name \"{0}\" Of Branch", campus), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
   await testRunner.AndAsync(string.Format("Click On Is Student Second Timer \"{0}\"", timer), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
   await testRunner.AndAsync(string.Format("Click On Student Academic Group \"{0}\"", group), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
   await testRunner.AndAsync(string.Format("Select Course Name \"{0}\" Of Program", course), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
  await testRunner.WhenAsync("Click On Admission Payment Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
  await testRunner.ThenAsync("Show Admission Payment Details Section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 68
  await testRunner.WhenAsync(string.Format("Enter Admission Received Amount \"{0}\"", received), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
  await testRunner.WhenAsync("Select Next Payment Receive Date", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
   await testRunner.AndAsync("Click On Old Admission Submit Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
  await testRunner.ThenAsync("Shown Admitted Money Receipt Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
   await testRunner.AndAsync("Evaluate Admission Money Receipt Data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="T1.2 Old Student Admission In Regular Course")]
        [Xunit.TraitAttribute("FeatureTitle", "Student Admission")]
        [Xunit.TraitAttribute("Description", "T1.2 Old Student Admission In Regular Course")]
        [Xunit.TraitAttribute("Category", "OldStudentAdmission")]
        [Xunit.TraitAttribute("Category", "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx")]
        [Xunit.TraitAttribute("Category", "DataSet:OldAdmission")]
        [Xunit.InlineDataAttribute("UDVASH", "", "", "Male", "Islam", "Admission", "68", "2024", "Bangla", "Rajshahi Udvash", "Rajshahi Campus", "No", "Science", "1422", "0", "2000", "2", "Branch Incharge", "4", "Special Discount", new string[0])]
        public async System.Threading.Tasks.Task T1_2OldStudentAdmissionInRegularCourse(
                    string organization, 
                    string regOrRoll, 
                    string mobile, 
                    string gender, 
                    string religion, 
                    string @class, 
                    string program, 
                    string session, 
                    string version, 
                    string branch, 
                    string campus, 
                    string timer, 
                    string group, 
                    string course, 
                    string received, 
                    string discount, 
                    string approvedBy, 
                    string discountType, 
                    string referredBy, 
                    string specialNote, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "OldStudentAdmission",
                    "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx",
                    "DataSet:OldAdmission"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Organization", organization);
            argumentsOfScenario.Add("RegOrRoll", regOrRoll);
            argumentsOfScenario.Add("Mobile", mobile);
            argumentsOfScenario.Add("Gender", gender);
            argumentsOfScenario.Add("Religion", religion);
            argumentsOfScenario.Add("Class", @class);
            argumentsOfScenario.Add("Program", program);
            argumentsOfScenario.Add("Session", session);
            argumentsOfScenario.Add("Version", version);
            argumentsOfScenario.Add("Branch", branch);
            argumentsOfScenario.Add("Campus", campus);
            argumentsOfScenario.Add("Timer", timer);
            argumentsOfScenario.Add("Group", group);
            argumentsOfScenario.Add("Course", course);
            argumentsOfScenario.Add("Received", received);
            argumentsOfScenario.Add("Discount", discount);
            argumentsOfScenario.Add("ApprovedBy", approvedBy);
            argumentsOfScenario.Add("DiscountType", discountType);
            argumentsOfScenario.Add("ReferredBy", referredBy);
            argumentsOfScenario.Add("SpecialNote", specialNote);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("T1.2 Old Student Admission In Regular Course", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 77
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 78
 await testRunner.GivenAsync("Goto New Or Old Student Admission", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 79
  await testRunner.WhenAsync(string.Format("Enter Student RegOrRoll Number \"{0}\"", regOrRoll), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 80
   await testRunner.AndAsync("Navigate Old Student Admission", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
  await testRunner.ThenAsync("Shown Old Student Admission Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 82
  await testRunner.WhenAsync(string.Format("Enter The Student Mobile Number \"{0}\"", mobile), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 83
   await testRunner.AndAsync(string.Format("Select Student Class \"{0}\" Type", @class), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
   await testRunner.AndAsync(string.Format("Select Student Program \"{0}\" Name", program), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
   await testRunner.AndAsync(string.Format("Select Session \"{0}\" Of Program", session), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
   await testRunner.AndAsync("Search Educational Institute Name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
  await testRunner.WhenAsync(string.Format("Select Branch Name \"{0}\" Of Program", branch), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 88
   await testRunner.AndAsync(string.Format("Select Campus Name \"{0}\" Of Branch", campus), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
   await testRunner.AndAsync(string.Format("Click On Is Student Second Timer \"{0}\"", timer), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
   await testRunner.AndAsync(string.Format("Click On Student Academic Group \"{0}\"", group), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
   await testRunner.AndAsync(string.Format("Select Course Name \"{0}\" Of Program", course), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
  await testRunner.WhenAsync("Click On Admission Payment Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 93
  await testRunner.ThenAsync("Show Admission Payment Details Section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 94
  await testRunner.WhenAsync(string.Format("Enter Admission Received Amount \"{0}\"", received), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 95
  await testRunner.WhenAsync("Select Next Payment Receive Date", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 96
   await testRunner.AndAsync("Click On Old Admission Submit Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
  await testRunner.ThenAsync("Shown Admitted Money Receipt Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 98
   await testRunner.AndAsync("Evaluate Admission Money Receipt Data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="T1.3 Old Admission in Same Program Session")]
        [Xunit.TraitAttribute("FeatureTitle", "Student Admission")]
        [Xunit.TraitAttribute("Description", "T1.3 Old Admission in Same Program Session")]
        [Xunit.TraitAttribute("Category", "OldStudentAdmissionInSameProgram")]
        [Xunit.TraitAttribute("Category", "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx")]
        [Xunit.TraitAttribute("Category", "DataSet:OldAdmission")]
        [Xunit.InlineDataAttribute("UDVASH", "", "", "Male", "Islam", "Admission", "68", "2024", "Bangla", "Rajshahi Udvash", "Rajshahi Campus", "No", "Science", "1422", "0", "2000", "2", "Branch Incharge", "4", "Special Discount", new string[0])]
        public async System.Threading.Tasks.Task T1_3OldAdmissionInSameProgramSession(
                    string organization, 
                    string regOrRoll, 
                    string mobile, 
                    string gender, 
                    string religion, 
                    string @class, 
                    string program, 
                    string session, 
                    string version, 
                    string branch, 
                    string campus, 
                    string timer, 
                    string group, 
                    string course, 
                    string received, 
                    string discount, 
                    string approvedBy, 
                    string discountType, 
                    string referredBy, 
                    string specialNote, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "OldStudentAdmissionInSameProgram",
                    "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx",
                    "DataSet:OldAdmission"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Organization", organization);
            argumentsOfScenario.Add("RegOrRoll", regOrRoll);
            argumentsOfScenario.Add("Mobile", mobile);
            argumentsOfScenario.Add("Gender", gender);
            argumentsOfScenario.Add("Religion", religion);
            argumentsOfScenario.Add("Class", @class);
            argumentsOfScenario.Add("Program", program);
            argumentsOfScenario.Add("Session", session);
            argumentsOfScenario.Add("Version", version);
            argumentsOfScenario.Add("Branch", branch);
            argumentsOfScenario.Add("Campus", campus);
            argumentsOfScenario.Add("Timer", timer);
            argumentsOfScenario.Add("Group", group);
            argumentsOfScenario.Add("Course", course);
            argumentsOfScenario.Add("Received", received);
            argumentsOfScenario.Add("Discount", discount);
            argumentsOfScenario.Add("ApprovedBy", approvedBy);
            argumentsOfScenario.Add("DiscountType", discountType);
            argumentsOfScenario.Add("ReferredBy", referredBy);
            argumentsOfScenario.Add("SpecialNote", specialNote);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("T1.3 Old Admission in Same Program Session", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 103
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 104
 await testRunner.GivenAsync("Navigate New Student Admission", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 105
  await testRunner.ThenAsync("Shown New Student Admission Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 106
  await testRunner.WhenAsync("Enter The Student Nickname \"<Nickname>\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 107
   await testRunner.AndAsync(string.Format("Enter The Student Mobile Number \"{0}\"", mobile), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 108
   await testRunner.AndAsync(string.Format("Select Student Gender \"{0}\"", gender), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
   await testRunner.AndAsync(string.Format("Select Student Religion \"{0}\"", religion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 110
   await testRunner.AndAsync(string.Format("Select Student Class \"{0}\" Type", @class), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 111
   await testRunner.AndAsync(string.Format("Select Student Program \"{0}\" Name", program), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 112
   await testRunner.AndAsync(string.Format("Select Session \"{0}\" Of Program", session), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 113
   await testRunner.AndAsync("Search Educational Institute Name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
   await testRunner.AndAsync(string.Format("Select Study Version \"{0}\" Type", version), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 115
   await testRunner.AndAsync(string.Format("Select Branch Name \"{0}\" Of Program", branch), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
   await testRunner.AndAsync(string.Format("Select Campus Name \"{0}\" Of Branch", campus), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 117
   await testRunner.AndAsync(string.Format("Click On Is Student Second Timer \"{0}\"", timer), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 118
   await testRunner.AndAsync(string.Format("Click On Student Academic Group \"{0}\"", group), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 119
   await testRunner.AndAsync(string.Format("Select Course Name \"{0}\" Of Program", course), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 120
  await testRunner.WhenAsync("Click On Admission Payment Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 121
  await testRunner.ThenAsync("Show Admission Payment Details Section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 122
  await testRunner.WhenAsync(string.Format("Enter Admission Received Amount \"{0}\"", received), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 123
   await testRunner.AndAsync("Select Next Payment Receive Date", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
   await testRunner.AndAsync("Click On New Admission Submit Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
  await testRunner.ThenAsync("Shown Admitted Money Receipt Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 126
   await testRunner.AndAsync("Evaluate Admission Money Receipt Data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
 await testRunner.GivenAsync("Goto New Or Old Student Admission", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 128
  await testRunner.WhenAsync(string.Format("Enter Student RegOrRoll Number \"{0}\"", regOrRoll), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 129
   await testRunner.AndAsync("Navigate Old Student Admission", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 130
  await testRunner.ThenAsync("Shown Old Student Admission Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 131
  await testRunner.WhenAsync(string.Format("Enter The Student Mobile Number \"{0}\"", mobile), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 132
   await testRunner.AndAsync(string.Format("Select Student Class \"{0}\" Type", @class), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 133
   await testRunner.AndAsync(string.Format("Select Student Program \"{0}\" Name", program), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
   await testRunner.AndAsync(string.Format("Select Session \"{0}\" Of Program", session), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 135
   await testRunner.AndAsync("Search Educational Institute Name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 136
  await testRunner.WhenAsync(string.Format("Select Branch Name \"{0}\" Of Program", branch), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 137
   await testRunner.AndAsync(string.Format("Select Campus Name \"{0}\" Of Branch", campus), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 138
   await testRunner.AndAsync(string.Format("Click On Is Student Second Timer \"{0}\"", timer), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 139
   await testRunner.AndAsync(string.Format("Click On Student Academic Group \"{0}\"", group), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 140
   await testRunner.AndAsync(string.Format("Select Course Name \"{0}\" Of Program", course), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 141
  await testRunner.ThenAsync("Can Take Any Course of This Program", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="T1.4 Special Discount New Student Admission")]
        [Xunit.TraitAttribute("FeatureTitle", "Student Admission")]
        [Xunit.TraitAttribute("Description", "T1.4 Special Discount New Student Admission")]
        [Xunit.TraitAttribute("Category", "SpecialDiscountNewStudentAdmission")]
        [Xunit.TraitAttribute("Category", "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx")]
        [Xunit.TraitAttribute("Category", "DataSet:OldAdmission")]
        [Xunit.InlineDataAttribute("UDVASH", "", "", "Male", "Islam", "Admission", "68", "2024", "Bangla", "Rajshahi Udvash", "Rajshahi Campus", "No", "Science", "1422", "0", "2000", "2", "Branch Incharge", "4", "Special Discount", new string[0])]
        public async System.Threading.Tasks.Task T1_4SpecialDiscountNewStudentAdmission(
                    string organization, 
                    string regOrRoll, 
                    string mobile, 
                    string gender, 
                    string religion, 
                    string @class, 
                    string program, 
                    string session, 
                    string version, 
                    string branch, 
                    string campus, 
                    string timer, 
                    string group, 
                    string course, 
                    string received, 
                    string discount, 
                    string approvedBy, 
                    string discountType, 
                    string referredBy, 
                    string specialNote, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SpecialDiscountNewStudentAdmission",
                    "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx",
                    "DataSet:OldAdmission"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Organization", organization);
            argumentsOfScenario.Add("RegOrRoll", regOrRoll);
            argumentsOfScenario.Add("Mobile", mobile);
            argumentsOfScenario.Add("Gender", gender);
            argumentsOfScenario.Add("Religion", religion);
            argumentsOfScenario.Add("Class", @class);
            argumentsOfScenario.Add("Program", program);
            argumentsOfScenario.Add("Session", session);
            argumentsOfScenario.Add("Version", version);
            argumentsOfScenario.Add("Branch", branch);
            argumentsOfScenario.Add("Campus", campus);
            argumentsOfScenario.Add("Timer", timer);
            argumentsOfScenario.Add("Group", group);
            argumentsOfScenario.Add("Course", course);
            argumentsOfScenario.Add("Received", received);
            argumentsOfScenario.Add("Discount", discount);
            argumentsOfScenario.Add("ApprovedBy", approvedBy);
            argumentsOfScenario.Add("DiscountType", discountType);
            argumentsOfScenario.Add("ReferredBy", referredBy);
            argumentsOfScenario.Add("SpecialNote", specialNote);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("T1.4 Special Discount New Student Admission", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 146
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 147
 await testRunner.GivenAsync("Navigate New Student Admission", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 148
  await testRunner.ThenAsync("Shown New Student Admission Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 149
  await testRunner.WhenAsync("Enter The Student Nickname \"<Nickname>\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 150
   await testRunner.AndAsync(string.Format("Enter The Student Mobile Number \"{0}\"", mobile), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 151
   await testRunner.AndAsync(string.Format("Select Student Gender \"{0}\"", gender), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 152
   await testRunner.AndAsync(string.Format("Select Student Religion \"{0}\"", religion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 153
   await testRunner.AndAsync(string.Format("Select Student Class \"{0}\" Type", @class), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 154
   await testRunner.AndAsync(string.Format("Select Student Program \"{0}\" Name", program), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 155
   await testRunner.AndAsync(string.Format("Select Session \"{0}\" Of Program", session), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 156
   await testRunner.AndAsync("Search Educational Institute Name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 157
  await testRunner.WhenAsync(string.Format("Select Study Version \"{0}\" Type", version), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 158
   await testRunner.AndAsync(string.Format("Select Branch Name \"{0}\" Of Program", branch), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 159
   await testRunner.AndAsync(string.Format("Select Campus Name \"{0}\" Of Branch", campus), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 160
   await testRunner.AndAsync(string.Format("Click On Is Student Second Timer \"{0}\"", timer), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 161
   await testRunner.AndAsync(string.Format("Click On Student Academic Group \"{0}\"", group), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 162
   await testRunner.AndAsync(string.Format("Select Course Name \"{0}\" Of Program", course), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 163
  await testRunner.WhenAsync("Click On Admission Payment Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 164
  await testRunner.ThenAsync("Show Admission Payment Details Section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 165
  await testRunner.WhenAsync(string.Format("Enter Special Discount \"{0}\" Amount", discount), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 166
   await testRunner.AndAsync(string.Format("Select Special Discount Approved By \"{0}\"", approvedBy), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 168
   await testRunner.AndAsync(string.Format("Select Special Discount Type \"{0}\"", discountType), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 169
   await testRunner.AndAsync(string.Format("Select Special Discount Referred By \"{0}\"", referredBy), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 171
   await testRunner.AndAsync("Enter Admission Special Discount Note", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 172
   await testRunner.AndAsync(string.Format("Enter Admission Received Amount \"{0}\"", received), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 173
   await testRunner.AndAsync("Select Next Payment Receive Date", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 174
    await testRunner.AndAsync("Click On New Admission Submit Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 175
  await testRunner.ThenAsync("Shown Admitted Money Receipt Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 176
     await testRunner.AndAsync("Evaluate Admission Money Receipt Data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="T1.5 Full Paid New Student Admission")]
        [Xunit.TraitAttribute("FeatureTitle", "Student Admission")]
        [Xunit.TraitAttribute("Description", "T1.5 Full Paid New Student Admission")]
        [Xunit.TraitAttribute("Category", "FullPaymentNewStudentAdmission")]
        [Xunit.TraitAttribute("Category", "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx")]
        [Xunit.TraitAttribute("Category", "DataSet:FullPayment")]
        [Xunit.InlineDataAttribute("UDVASH", "", "", "", "Male", "Islam", "Eleven", "62", "2024", "Bangla", "Basabo Udvash", "Basabo Campus", "No", "Science", "1306", "", "2000", "2", "Top Student", "4", "Special Discount", new string[0])]
        public async System.Threading.Tasks.Task T1_5FullPaidNewStudentAdmission(
                    string organization, 
                    string nickname, 
                    string regOrRoll, 
                    string mobile, 
                    string gender, 
                    string religion, 
                    string @class, 
                    string program, 
                    string session, 
                    string version, 
                    string branch, 
                    string campus, 
                    string timer, 
                    string group, 
                    string course, 
                    string received, 
                    string discount, 
                    string approvedBy, 
                    string discountType, 
                    string referredBy, 
                    string specialNote, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "FullPaymentNewStudentAdmission",
                    "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx",
                    "DataSet:FullPayment"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Organization", organization);
            argumentsOfScenario.Add("Nickname", nickname);
            argumentsOfScenario.Add("RegOrRoll", regOrRoll);
            argumentsOfScenario.Add("Mobile", mobile);
            argumentsOfScenario.Add("Gender", gender);
            argumentsOfScenario.Add("Religion", religion);
            argumentsOfScenario.Add("Class", @class);
            argumentsOfScenario.Add("Program", program);
            argumentsOfScenario.Add("Session", session);
            argumentsOfScenario.Add("Version", version);
            argumentsOfScenario.Add("Branch", branch);
            argumentsOfScenario.Add("Campus", campus);
            argumentsOfScenario.Add("Timer", timer);
            argumentsOfScenario.Add("Group", group);
            argumentsOfScenario.Add("Course", course);
            argumentsOfScenario.Add("Received", received);
            argumentsOfScenario.Add("Discount", discount);
            argumentsOfScenario.Add("ApprovedBy", approvedBy);
            argumentsOfScenario.Add("DiscountType", discountType);
            argumentsOfScenario.Add("ReferredBy", referredBy);
            argumentsOfScenario.Add("SpecialNote", specialNote);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("T1.5 Full Paid New Student Admission", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 181
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 182
 await testRunner.GivenAsync("Navigate New Student Admission", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 183
  await testRunner.ThenAsync("Shown New Student Admission Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 184
  await testRunner.WhenAsync(string.Format("Enter The Student Nickname \"{0}\"", nickname), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 185
   await testRunner.AndAsync(string.Format("Enter The Student Mobile Number \"{0}\"", mobile), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 186
   await testRunner.AndAsync(string.Format("Select Student Gender \"{0}\"", gender), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 187
   await testRunner.AndAsync(string.Format("Select Student Religion \"{0}\"", religion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 188
   await testRunner.AndAsync(string.Format("Select Student Class \"{0}\" Type", @class), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 189
   await testRunner.AndAsync(string.Format("Select Student Program \"{0}\" Name", program), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 190
   await testRunner.AndAsync(string.Format("Select Session \"{0}\" Of Program", session), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 191
   await testRunner.AndAsync("Search Educational Institute Name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 192
   await testRunner.AndAsync(string.Format("Select Study Version \"{0}\" Type", version), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 193
   await testRunner.AndAsync(string.Format("Select Branch Name \"{0}\" Of Program", branch), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 194
   await testRunner.AndAsync(string.Format("Select Campus Name \"{0}\" Of Branch", campus), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 195
   await testRunner.AndAsync(string.Format("Click On Is Student Second Timer \"{0}\"", timer), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 196
   await testRunner.AndAsync(string.Format("Click On Student Academic Group \"{0}\"", group), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 197
   await testRunner.AndAsync(string.Format("Select Course Name \"{0}\" Of Program", course), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 198
  await testRunner.WhenAsync("Click On Admission Payment Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 199
  await testRunner.ThenAsync("Show Admission Payment Details Section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 200
  await testRunner.WhenAsync(string.Format("Enter Full Receivable Amount \"{0}\"", received), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 201
   await testRunner.AndAsync("Select Next Payment Receive Date", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 202
   await testRunner.AndAsync("Click On New Admission Submit Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 203
  await testRunner.ThenAsync("Shown Admitted Money Receipt Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 204
   await testRunner.AndAsync("Evaluate Admission Money Receipt Data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="T1.6 Full Discount New Student Admission")]
        [Xunit.TraitAttribute("FeatureTitle", "Student Admission")]
        [Xunit.TraitAttribute("Description", "T1.6 Full Discount New Student Admission")]
        [Xunit.TraitAttribute("Category", "FullDiscountNewStudentAdmission")]
        [Xunit.TraitAttribute("Category", "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx")]
        [Xunit.TraitAttribute("Category", "DataSet:FullDiscount")]
        [Xunit.InlineDataAttribute("UDVASH", "", "", "", "Male", "Islam", "Admission", "68", "2024", "Bangla", "Mirpur Udvash", "Stadium Campus", "No", "Science", "1422", "", "2000", "2", "Top Student", "4", "Special Discount", new string[0])]
        public async System.Threading.Tasks.Task T1_6FullDiscountNewStudentAdmission(
                    string organization, 
                    string nickname, 
                    string regOrRoll, 
                    string mobile, 
                    string gender, 
                    string religion, 
                    string @class, 
                    string program, 
                    string session, 
                    string version, 
                    string branch, 
                    string campus, 
                    string timer, 
                    string group, 
                    string course, 
                    string received, 
                    string discount, 
                    string approvedBy, 
                    string discountType, 
                    string referredBy, 
                    string specialNote, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "FullDiscountNewStudentAdmission",
                    "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx",
                    "DataSet:FullDiscount"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Organization", organization);
            argumentsOfScenario.Add("Nickname", nickname);
            argumentsOfScenario.Add("RegOrRoll", regOrRoll);
            argumentsOfScenario.Add("Mobile", mobile);
            argumentsOfScenario.Add("Gender", gender);
            argumentsOfScenario.Add("Religion", religion);
            argumentsOfScenario.Add("Class", @class);
            argumentsOfScenario.Add("Program", program);
            argumentsOfScenario.Add("Session", session);
            argumentsOfScenario.Add("Version", version);
            argumentsOfScenario.Add("Branch", branch);
            argumentsOfScenario.Add("Campus", campus);
            argumentsOfScenario.Add("Timer", timer);
            argumentsOfScenario.Add("Group", group);
            argumentsOfScenario.Add("Course", course);
            argumentsOfScenario.Add("Received", received);
            argumentsOfScenario.Add("Discount", discount);
            argumentsOfScenario.Add("ApprovedBy", approvedBy);
            argumentsOfScenario.Add("DiscountType", discountType);
            argumentsOfScenario.Add("ReferredBy", referredBy);
            argumentsOfScenario.Add("SpecialNote", specialNote);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("T1.6 Full Discount New Student Admission", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 209
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 210
 await testRunner.GivenAsync("Navigate New Student Admission", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 211
  await testRunner.ThenAsync("Shown New Student Admission Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 212
  await testRunner.WhenAsync(string.Format("Enter The Student Nickname \"{0}\"", nickname), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 213
   await testRunner.AndAsync(string.Format("Enter The Student Mobile Number \"{0}\"", mobile), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 214
   await testRunner.AndAsync(string.Format("Select Student Gender \"{0}\"", gender), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 215
   await testRunner.AndAsync(string.Format("Select Student Religion \"{0}\"", religion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 216
   await testRunner.AndAsync(string.Format("Select Student Class \"{0}\" Type", @class), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 217
   await testRunner.AndAsync(string.Format("Select Student Program \"{0}\" Name", program), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 218
   await testRunner.AndAsync(string.Format("Select Session \"{0}\" Of Program", session), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 219
   await testRunner.AndAsync("Search Educational Institute Name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 220
  await testRunner.WhenAsync(string.Format("Select Study Version \"{0}\" Type", version), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 221
   await testRunner.AndAsync(string.Format("Select Branch Name \"{0}\" Of Program", branch), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 222
   await testRunner.AndAsync(string.Format("Select Campus Name \"{0}\" Of Branch", campus), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 223
   await testRunner.AndAsync(string.Format("Click On Is Student Second Timer \"{0}\"", timer), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 224
   await testRunner.AndAsync(string.Format("Click On Student Academic Group \"{0}\"", group), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 225
   await testRunner.AndAsync(string.Format("Select Course Name \"{0}\" Of Program", course), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 226
   await testRunner.AndAsync("Click On Admission Payment Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 227
  await testRunner.ThenAsync("Show Admission Payment Details Section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 228
  await testRunner.WhenAsync("Enter Full Discount Amount For Top Student", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 229
   await testRunner.AndAsync(string.Format("Select Special Discount Approved By \"{0}\"", approvedBy), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 230
   await testRunner.AndAsync(string.Format("Select Special Discount Type \"{0}\"", discountType), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 231
   await testRunner.AndAsync(string.Format("Select Special Discount Referred By \"{0}\"", referredBy), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 232
   await testRunner.AndAsync("Enter Admission Special Discount Note", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 233
   await testRunner.AndAsync(string.Format("Enter Admission Received Amount \"{0}\"", received), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 234
   await testRunner.AndAsync("Select Next Payment Receive Date", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 235
    await testRunner.AndAsync("Click On New Admission Submit Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 236
  await testRunner.ThenAsync("Shown Admitted Money Receipt Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 237
     await testRunner.AndAsync("Evaluate Admission Money Receipt Data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="T1.7 Minimum Amount Over Payable Amount New Admission")]
        [Xunit.TraitAttribute("FeatureTitle", "Student Admission")]
        [Xunit.TraitAttribute("Description", "T1.7 Minimum Amount Over Payable Amount New Admission")]
        [Xunit.TraitAttribute("Category", "OverMinAmountNewStudentAdmission")]
        [Xunit.TraitAttribute("Category", "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx")]
        [Xunit.TraitAttribute("Category", "DataSet:Sp_Discount")]
        [Xunit.InlineDataAttribute("UDVASH", "", "", "", "Male", "Islam", "Admission", "68", "2024", "Bangla", "Mirpur Udvash", "Stadium Campus", "No", "Science", "1422", "", "15000", "2", "Top Student", "4", "Special Discount", new string[0])]
        public async System.Threading.Tasks.Task T1_7MinimumAmountOverPayableAmountNewAdmission(
                    string organization, 
                    string nickname, 
                    string regOrRoll, 
                    string mobile, 
                    string gender, 
                    string religion, 
                    string @class, 
                    string program, 
                    string session, 
                    string version, 
                    string branch, 
                    string campus, 
                    string timer, 
                    string group, 
                    string course, 
                    string received, 
                    string discount, 
                    string approvedBy, 
                    string discountType, 
                    string referredBy, 
                    string specialNote, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "OverMinAmountNewStudentAdmission",
                    "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx",
                    "DataSet:Sp_Discount"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Organization", organization);
            argumentsOfScenario.Add("Nickname", nickname);
            argumentsOfScenario.Add("RegOrRoll", regOrRoll);
            argumentsOfScenario.Add("Mobile", mobile);
            argumentsOfScenario.Add("Gender", gender);
            argumentsOfScenario.Add("Religion", religion);
            argumentsOfScenario.Add("Class", @class);
            argumentsOfScenario.Add("Program", program);
            argumentsOfScenario.Add("Session", session);
            argumentsOfScenario.Add("Version", version);
            argumentsOfScenario.Add("Branch", branch);
            argumentsOfScenario.Add("Campus", campus);
            argumentsOfScenario.Add("Timer", timer);
            argumentsOfScenario.Add("Group", group);
            argumentsOfScenario.Add("Course", course);
            argumentsOfScenario.Add("Received", received);
            argumentsOfScenario.Add("Discount", discount);
            argumentsOfScenario.Add("ApprovedBy", approvedBy);
            argumentsOfScenario.Add("DiscountType", discountType);
            argumentsOfScenario.Add("ReferredBy", referredBy);
            argumentsOfScenario.Add("SpecialNote", specialNote);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("T1.7 Minimum Amount Over Payable Amount New Admission", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 242
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 243
 await testRunner.GivenAsync("Navigate New Student Admission", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 244
  await testRunner.ThenAsync("Shown New Student Admission Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 245
  await testRunner.WhenAsync(string.Format("Enter The Student Nickname \"{0}\"", nickname), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 246
   await testRunner.AndAsync(string.Format("Enter The Student Mobile Number \"{0}\"", mobile), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 247
   await testRunner.AndAsync(string.Format("Select Student Gender \"{0}\"", gender), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 248
   await testRunner.AndAsync(string.Format("Select Student Religion \"{0}\"", religion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 249
   await testRunner.AndAsync(string.Format("Select Student Class \"{0}\" Type", @class), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 250
   await testRunner.AndAsync(string.Format("Select Student Program \"{0}\" Name", program), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 251
   await testRunner.AndAsync(string.Format("Select Session \"{0}\" Of Program", session), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 252
   await testRunner.AndAsync("Search Educational Institute Name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 253
  await testRunner.WhenAsync(string.Format("Select Study Version \"{0}\" Type", version), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 254
   await testRunner.AndAsync(string.Format("Select Branch Name \"{0}\" Of Program", branch), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 255
   await testRunner.AndAsync(string.Format("Select Campus Name \"{0}\" Of Branch", campus), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 256
   await testRunner.AndAsync(string.Format("Click On Is Student Second Timer \"{0}\"", timer), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 257
   await testRunner.AndAsync(string.Format("Click On Student Academic Group \"{0}\"", group), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 258
   await testRunner.AndAsync(string.Format("Select Course Name \"{0}\" Of Program", course), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 259
  await testRunner.WhenAsync("Click On Admission Payment Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 260
  await testRunner.ThenAsync("Show Admission Payment Details Section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 261
  await testRunner.WhenAsync(string.Format("Enter Special Discount \"{0}\" Amount", discount), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 262
   await testRunner.AndAsync(string.Format("Select Special Discount Approved By \"{0}\"", approvedBy), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 263
   await testRunner.AndAsync(string.Format("Select Special Discount Type \"{0}\"", discountType), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 265
   await testRunner.AndAsync("Enter Admission Special Discount Note", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 266
   await testRunner.AndAsync(string.Format("Enter Admission Received Amount \"{0}\"", received), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 267
   await testRunner.AndAsync("Select Next Payment Receive Date", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 268
    await testRunner.AndAsync("Click On New Admission Submit Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 269
  await testRunner.ThenAsync("Shown Admitted Money Receipt Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 270
     await testRunner.AndAsync("Evaluate Admission Money Receipt Data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="T1.8 New Admission in Complementary Course")]
        [Xunit.TraitAttribute("FeatureTitle", "Student Admission")]
        [Xunit.TraitAttribute("Description", "T1.8 New Admission in Complementary Course")]
        [Xunit.TraitAttribute("Category", "ComplementaryNewStudentAdmission")]
        [Xunit.TraitAttribute("Category", "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx")]
        [Xunit.TraitAttribute("Category", "DataSet:Complementary")]
        [Xunit.InlineDataAttribute("UDVASH", "", "", "Male", "Islam", "Admission", "68", "2024", "Bangla", "Barishal Udvash", "Barishal Campus", "Online Campus", "Barishal Unmesh", " No", "Science", "1910", "Medical 2nd Time Special Course", "", "2000", "2", "Branch Incharge", "4", "Special Discount", new string[0])]
        public async System.Threading.Tasks.Task T1_8NewAdmissionInComplementaryCourse(
                    string organization, 
                    string regOrRoll, 
                    string mobile, 
                    string gender, 
                    string religion, 
                    string @class, 
                    string program, 
                    string session, 
                    string version, 
                    string branch, 
                    string campus, 
                    string campus2, 
                    string attachedBranch, 
                    string timer, 
                    string group, 
                    string course, 
                    string complementaryCourse, 
                    string received, 
                    string discount, 
                    string approvedBy, 
                    string discountType, 
                    string referredBy, 
                    string specialNote, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ComplementaryNewStudentAdmission",
                    "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx",
                    "DataSet:Complementary"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Organization", organization);
            argumentsOfScenario.Add("RegOrRoll", regOrRoll);
            argumentsOfScenario.Add("Mobile", mobile);
            argumentsOfScenario.Add("Gender", gender);
            argumentsOfScenario.Add("Religion", religion);
            argumentsOfScenario.Add("Class", @class);
            argumentsOfScenario.Add("Program", program);
            argumentsOfScenario.Add("Session", session);
            argumentsOfScenario.Add("Version", version);
            argumentsOfScenario.Add("Branch", branch);
            argumentsOfScenario.Add("Campus", campus);
            argumentsOfScenario.Add("Campus2", campus2);
            argumentsOfScenario.Add("AttachedBranch", attachedBranch);
            argumentsOfScenario.Add("Timer", timer);
            argumentsOfScenario.Add("Group", group);
            argumentsOfScenario.Add("Course", course);
            argumentsOfScenario.Add("ComplementaryCourse", complementaryCourse);
            argumentsOfScenario.Add("Received", received);
            argumentsOfScenario.Add("Discount", discount);
            argumentsOfScenario.Add("ApprovedBy", approvedBy);
            argumentsOfScenario.Add("DiscountType", discountType);
            argumentsOfScenario.Add("ReferredBy", referredBy);
            argumentsOfScenario.Add("SpecialNote", specialNote);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("T1.8 New Admission in Complementary Course", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 275
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 276
 await testRunner.GivenAsync("Navigate New Student Admission", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 277
  await testRunner.ThenAsync("Shown New Student Admission Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 278
  await testRunner.WhenAsync("Enter The Student Nickname \"<Nickname>\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 279
   await testRunner.AndAsync(string.Format("Enter The Student Mobile Number \"{0}\"", mobile), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 280
   await testRunner.AndAsync(string.Format("Select Student Gender \"{0}\"", gender), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 281
   await testRunner.AndAsync(string.Format("Select Student Religion \"{0}\"", religion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 282
   await testRunner.AndAsync(string.Format("Select Student Class \"{0}\" Type", @class), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 283
   await testRunner.AndAsync(string.Format("Select Student Program \"{0}\" Name", program), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 284
   await testRunner.AndAsync(string.Format("Select Session \"{0}\" Of Program", session), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 285
   await testRunner.AndAsync("Search Educational Institute Name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 286
  await testRunner.WhenAsync(string.Format("Select Study Version \"{0}\" Type", version), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 287
   await testRunner.AndAsync(string.Format("Select Branch Name \"{0}\" Of Program", branch), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 288
   await testRunner.AndAsync(string.Format("Select Campus Name \"{0}\" Of Branch", campus), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 289
   await testRunner.AndAsync(string.Format("Click On Is Student Second Timer \"{0}\"", timer), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 290
   await testRunner.AndAsync(string.Format("Click On Student Academic Group \"{0}\"", group), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 291
   await testRunner.AndAsync(string.Format("Click On Complementary Course Name \"{0}\"", complementaryCourse), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 292
  await testRunner.WhenAsync("Click On Confirm Button In Modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 293
  await testRunner.ThenAsync("Is Show Complementary Course List", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 294
  await testRunner.WhenAsync(string.Format("Select Branch Name \"{0}\" Of Program", attachedBranch), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 295
   await testRunner.AndAsync(string.Format("Select Campus Name \"{0}\" Of Branch", campus), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 296
   await testRunner.AndAsync(string.Format("Select Course Name \"{0}\" Of Program", course), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 297
  await testRunner.WhenAsync("Click On Admission Payment Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 298
  await testRunner.ThenAsync("Show Admission Payment Details Section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 299
  await testRunner.WhenAsync(string.Format("Enter Admission Received Amount \"{0}\"", received), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 300
   await testRunner.AndAsync("Select Next Payment Receive Date", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 301
   await testRunner.AndAsync("Click On New Admission Submit Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 302
  await testRunner.ThenAsync("Shown Admitted Money Receipt Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 303
   await testRunner.AndAsync("Evaluate Admission Money Receipt Data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="T1.9 Spin New Student Admission Test")]
        [Xunit.TraitAttribute("FeatureTitle", "Student Admission")]
        [Xunit.TraitAttribute("Description", "T1.9 Spin New Student Admission Test")]
        [Xunit.TraitAttribute("Category", "SpinNewAdmission")]
        [Xunit.TraitAttribute("Category", "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx")]
        [Xunit.TraitAttribute("Category", "DataSet:SpinAdmission")]
        [Xunit.InlineDataAttribute("UDVASH", "", "", "", "Male", "Islam", "Admission", "68", "2024", "Bangla", "Mirpur Udvash", "Stadium Campus", "No", "Science", "1422", "12000", "2000", "2", "Branch Incharge", "4", "Special Discount", "10", new string[0])]
        public async System.Threading.Tasks.Task T1_9SpinNewStudentAdmissionTest(
                    string organization, 
                    string nickname, 
                    string regOrRoll, 
                    string mobile, 
                    string gender, 
                    string religion, 
                    string @class, 
                    string program, 
                    string session, 
                    string version, 
                    string branch, 
                    string campus, 
                    string timer, 
                    string group, 
                    string course, 
                    string received, 
                    string discount, 
                    string approvedBy, 
                    string discountType, 
                    string referredBy, 
                    string specialNote, 
                    string count, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SpinNewAdmission",
                    "DataSource:../../../TestData/Student/Excel/AdmissionData.xlsx",
                    "DataSet:SpinAdmission"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Organization", organization);
            argumentsOfScenario.Add("Nickname", nickname);
            argumentsOfScenario.Add("RegOrRoll", regOrRoll);
            argumentsOfScenario.Add("Mobile", mobile);
            argumentsOfScenario.Add("Gender", gender);
            argumentsOfScenario.Add("Religion", religion);
            argumentsOfScenario.Add("Class", @class);
            argumentsOfScenario.Add("Program", program);
            argumentsOfScenario.Add("Session", session);
            argumentsOfScenario.Add("Version", version);
            argumentsOfScenario.Add("Branch", branch);
            argumentsOfScenario.Add("Campus", campus);
            argumentsOfScenario.Add("Timer", timer);
            argumentsOfScenario.Add("Group", group);
            argumentsOfScenario.Add("Course", course);
            argumentsOfScenario.Add("Received", received);
            argumentsOfScenario.Add("Discount", discount);
            argumentsOfScenario.Add("ApprovedBy", approvedBy);
            argumentsOfScenario.Add("DiscountType", discountType);
            argumentsOfScenario.Add("ReferredBy", referredBy);
            argumentsOfScenario.Add("SpecialNote", specialNote);
            argumentsOfScenario.Add("Count", count);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("T1.9 Spin New Student Admission Test", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 308
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 309
 await testRunner.GivenAsync("Navigate New Student Admission", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 310
  await testRunner.ThenAsync("Shown New Student Admission Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 311
  await testRunner.WhenAsync(string.Format("Enter The Student Nickname \"{0}\"", nickname), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 312
   await testRunner.AndAsync(string.Format("Enter The Student Mobile Number \"{0}\"", mobile), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 313
   await testRunner.AndAsync(string.Format("Select Student Gender \"{0}\"", gender), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 314
   await testRunner.AndAsync(string.Format("Select Student Religion \"{0}\"", religion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 315
   await testRunner.AndAsync(string.Format("Select Student Class \"{0}\" Type", @class), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 316
   await testRunner.AndAsync(string.Format("Select Student Program \"{0}\" Name", program), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 317
   await testRunner.AndAsync(string.Format("Select Session \"{0}\" Of Program", session), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 318
   await testRunner.AndAsync("Search Educational Institute Name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 319
   await testRunner.AndAsync(string.Format("Select Study Version \"{0}\" Type", version), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 320
   await testRunner.AndAsync(string.Format("Select Branch Name \"{0}\" Of Program", branch), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 321
   await testRunner.AndAsync(string.Format("Select Campus Name \"{0}\" Of Branch", campus), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 322
   await testRunner.AndAsync(string.Format("Click On Is Student Second Timer \"{0}\"", timer), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 323
   await testRunner.AndAsync(string.Format("Click On Student Academic Group \"{0}\"", group), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 325
   await testRunner.AndAsync(string.Format("Select Course Name \"{0}\"", course), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 326
   await testRunner.AndAsync("Select Batch Type Of This Course", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 327
   await testRunner.AndAsync("Select Batch Time Of This Course", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 328
   await testRunner.AndAsync("Select Batch Name Of This Course", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 329
   await testRunner.AndAsync("Click On Admission Payment Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 330
  await testRunner.ThenAsync("Show Admission Payment Details Section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 331
  await testRunner.WhenAsync(string.Format("Enter Admission Received Amount \"{0}\"", received), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 332
   await testRunner.AndAsync("Select Next Payment Receive Date", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 333
   await testRunner.AndAsync("Click On New Admission Submit Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 334
  await testRunner.ThenAsync("Shown Admitted Money Receipt Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 335
   await testRunner.AndAsync("Evaluate Admission Money Receipt Data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 336
  await testRunner.WhenAsync(string.Format("Bulk Spin New Student Admission \"{0}\"", count), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await StudentAdmissionFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await StudentAdmissionFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
