// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UMS.UI.Test.OnlinePortal.Areas.Student.Registration
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class StudentPortalRegistrationFeature : object, Xunit.IClassFixture<StudentPortalRegistrationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Areas/Student/Registration", "Student Portal Registration", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Registration.feature"
#line hidden
        
        public StudentPortalRegistrationFeature(StudentPortalRegistrationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="01 Student Registration Test")]
        [Xunit.TraitAttribute("FeatureTitle", "Student Portal Registration")]
        [Xunit.TraitAttribute("Description", "01 Student Registration Test")]
        [Xunit.TraitAttribute("Category", "StudentRegistration")]
        [Xunit.TraitAttribute("Category", "DataSource:../../../../UMS.UI.Test.OnlinePortal/TestData/Student/Excel/Registrati" +
            "on.xlsx")]
        [Xunit.TraitAttribute("Category", "DataSet:registrationinfo")]
        [Xunit.InlineDataAttribute("1", "Admission", "Male", "Islam", "Bagerhat", "", "123456", new string[0])]
        public async System.Threading.Tasks.Task _01StudentRegistrationTest(string sL, string gradeOrLevel, string gender, string religion, string district, string email, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "StudentRegistration",
                    "DataSource:../../../../UMS.UI.Test.OnlinePortal/TestData/Student/Excel/Registrati" +
                        "on.xlsx",
                    "DataSet:registrationinfo"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("SL", sL);
            argumentsOfScenario.Add("GradeOrLevel", gradeOrLevel);
            argumentsOfScenario.Add("Gender", gender);
            argumentsOfScenario.Add("Religion", religion);
            argumentsOfScenario.Add("District", district);
            argumentsOfScenario.Add("Email", email);
            argumentsOfScenario.Add("Password", password);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("01 Student Registration Test", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
 await testRunner.GivenAsync("Goto Student Registration Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
  await testRunner.WhenAsync("Click on the Register Now", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
  await testRunner.ThenAsync("Show Registration Form Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 11
  await testRunner.WhenAsync("Enter Nick Name in the field", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
   await testRunner.AndAsync("Enter Mobile Number in the field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
   await testRunner.AndAsync("Click on the Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
  await testRunner.ThenAsync("Show OTP Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 15
  await testRunner.WhenAsync("Enter OTP in the field", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
  await testRunner.AndAsync("Click on the OTP Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
  await testRunner.ThenAsync("Show Academic Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 19
  await testRunner.WhenAsync(string.Format("Select Grade or Level DropDown \"{0}\"", gradeOrLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
  await testRunner.AndAsync(string.Format("Select Gender DropDown \"{0}\"", gender), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
  await testRunner.AndAsync(string.Format("Select Religion DropDown \"{0}\"", religion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
  await testRunner.AndAsync(string.Format("Select District DropDown \"{0}\"", district), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
  await testRunner.AndAsync(string.Format("Enter Email in the field \"{0}\"", email), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
  await testRunner.AndAsync("Click on the Submit Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
  await testRunner.ThenAsync("Show Set Your Password Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 26
  await testRunner.WhenAsync(string.Format("Enter New Password in the field \"{0}\"", password), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
  await testRunner.AndAsync("Enter Confirm Password in the field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
  await testRunner.AndAsync("Click on the Set Password Submit Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
  await testRunner.ThenAsync("Show Program List Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="02 Student Forgot Registration Number Test")]
        [Xunit.TraitAttribute("FeatureTitle", "Student Portal Registration")]
        [Xunit.TraitAttribute("Description", "02 Student Forgot Registration Number Test")]
        [Xunit.TraitAttribute("Category", "ForgotRegistrationNumber")]
        public async System.Threading.Tasks.Task _02StudentForgotRegistrationNumberTest()
        {
            string[] tagsOfScenario = new string[] {
                    "ForgotRegistrationNumber"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("02 Student Forgot Registration Number Test", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 33
 await testRunner.GivenAsync("Goto Student Registration Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 34
  await testRunner.WhenAsync("Click on the Forgot Registration Number", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
  await testRunner.ThenAsync("Show Forgot Registration Number Form Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 36
  await testRunner.WhenAsync("Enter Forgot Registration Nick Name in the field", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
   await testRunner.AndAsync("Enter Forgot Registration Mobile Number in the field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
   await testRunner.AndAsync("Click on the Forgot Registration Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
  await testRunner.ThenAsync("Show Forgot Registration OTP Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 40
  await testRunner.WhenAsync("Enter Forgot Registration OTP in the field", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
  await testRunner.AndAsync("Click on the Forgot Registration OTP Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
  await testRunner.ThenAsync("Show Congratulations Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="03 Student Forgot Password Test")]
        [Xunit.TraitAttribute("FeatureTitle", "Student Portal Registration")]
        [Xunit.TraitAttribute("Description", "03 Student Forgot Password Test")]
        [Xunit.TraitAttribute("Category", "ForgotPassword")]
        public async System.Threading.Tasks.Task _03StudentForgotPasswordTest()
        {
            string[] tagsOfScenario = new string[] {
                    "ForgotPassword"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("03 Student Forgot Password Test", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 45
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 46
 await testRunner.GivenAsync("Goto Student Portal Login Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
  await testRunner.WhenAsync("Enter Registration Number in the field", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
   await testRunner.AndAsync("Click on the Student Login Next button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
   await testRunner.ThenAsync("Show Forgot Password Text", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
   await testRunner.WhenAsync("Click on the Forgot Password Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 51
   await testRunner.AndAsync("Enter Forgot Password Registration Number in the field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
   await testRunner.AndAsync("Enter Forgot Password Mobile Number in the field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
   await testRunner.AndAsync("Click on the Forgot Password Next button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
  await testRunner.ThenAsync("Show Forgot Password OTP Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 55
  await testRunner.WhenAsync("Enter Forgot Password OTP in the field", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
  await testRunner.AndAsync("Click on the Forgot Password OTP Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
  await testRunner.WhenAsync("Enter New Password in the field \"<Password>\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
  await testRunner.AndAsync("Enter Confirm Password in the field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
  await testRunner.AndAsync("Click on the Set Password Submit Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
  await testRunner.ThenAsync("Show Login Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="04 Student Registration Resend OTP Test")]
        [Xunit.TraitAttribute("FeatureTitle", "Student Portal Registration")]
        [Xunit.TraitAttribute("Description", "04 Student Registration Resend OTP Test")]
        [Xunit.TraitAttribute("Category", "RegistrationResendOTP")]
        public async System.Threading.Tasks.Task _04StudentRegistrationResendOTPTest()
        {
            string[] tagsOfScenario = new string[] {
                    "RegistrationResendOTP"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("04 Student Registration Resend OTP Test", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 63
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 64
 await testRunner.GivenAsync("Goto Student Registration Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 65
  await testRunner.WhenAsync("Click on the Forgot Registration Number", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
  await testRunner.ThenAsync("Show Forgot Registration Number Form Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 67
  await testRunner.WhenAsync("Enter Forgot Registration Nick Name in the field", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 68
   await testRunner.AndAsync("Enter Forgot Registration Mobile Number in the field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
   await testRunner.AndAsync("Click on the Forgot Registration Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
  await testRunner.ThenAsync("Show Forgot Registration OTP Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 71
  await testRunner.WhenAsync("Click Resend OTP Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 72
  await testRunner.WhenAsync("Enter Forgot Registration OTP in the field", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
  await testRunner.AndAsync("Click on the Forgot Registration OTP Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
  await testRunner.ThenAsync("Show Congratulations Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await StudentPortalRegistrationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await StudentPortalRegistrationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
