// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UMS.UI.Test.OnlinePortal.Areas.Student.Enrolment.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class StudentProgramEnrolmentFeature : object, Xunit.IClassFixture<StudentProgramEnrolmentFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Areas/Student/Enrolment/Features", "Student Program Enrolment", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ProgramEnrolment.feature"
#line hidden
        
        public StudentProgramEnrolmentFeature(StudentProgramEnrolmentFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Program Enrolment Test")]
        [Xunit.TraitAttribute("FeatureTitle", "Student Program Enrolment")]
        [Xunit.TraitAttribute("Description", "Program Enrolment Test")]
        [Xunit.TraitAttribute("Category", "ProgramEnrolment")]
        [Xunit.TraitAttribute("Category", "DataSource:../../../../TestData/Student/Excel/Enrolment.xlsx")]
        [Xunit.TraitAttribute("Category", "DataSet:Enroll")]
        [Xunit.InlineDataAttribute("1", "Admission", "Engineering Admission Program", "2024", "Engineering Full Course (Offline)", "108258", "Bangla", "Mirpur Udvash", "First Timer", "Science", "10000", "Nagad Web Payment", new string[0])]
        public async System.Threading.Tasks.Task ProgramEnrolmentTest(string sL, string classType, string program, string session, string course, string institute, string version, string branch, string mbbsDbs, string studyGroup, string paymentAmount, string paymentMethod, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ProgramEnrolment",
                    "DataSource:../../../../TestData/Student/Excel/Enrolment.xlsx",
                    "DataSet:Enroll"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("SL", sL);
            argumentsOfScenario.Add("ClassType", classType);
            argumentsOfScenario.Add("Program", program);
            argumentsOfScenario.Add("Session", session);
            argumentsOfScenario.Add("Course", course);
            argumentsOfScenario.Add("Institute", institute);
            argumentsOfScenario.Add("Version", version);
            argumentsOfScenario.Add("Branch", branch);
            argumentsOfScenario.Add("MbbsDbs", mbbsDbs);
            argumentsOfScenario.Add("StudyGroup", studyGroup);
            argumentsOfScenario.Add("PaymentAmount", paymentAmount);
            argumentsOfScenario.Add("PaymentMethod", paymentMethod);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Program Enrolment Test", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("Goto Student Program Enrolment Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
  await testRunner.WhenAsync(string.Format("Select Student Program Class Type \"{0}\"", classType), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
   await testRunner.AndAsync(string.Format("Click On Enroll Now Button \"{0}\" \"{1}\"", program, session), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
   await testRunner.AndAsync(string.Format("Select Desire Course Name \"{0}\"", course), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
   await testRunner.AndAsync("Click On Student Course Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
   await testRunner.AndAsync(string.Format("Select Student Institute Name \"{0}\"", institute), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
   await testRunner.AndAsync(string.Format("Select Student Study Version \"{0}\"", version), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
   await testRunner.AndAsync(string.Format("Select Student Course Branch \"{0}\"", branch), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
   await testRunner.AndAsync(string.Format("Select Attached Physical Branch \"{0}\"", branch), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
   await testRunner.AndAsync(string.Format("Select Mbbs Or Dbs Second Time Status \"{0}\"", mbbsDbs), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
   await testRunner.AndAsync(string.Format("Select Student Academic Study Group \"{0}\"", studyGroup), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
   await testRunner.AndAsync(string.Format("Select Course Batch Type, Time & Name \"{0}\"", course), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
   await testRunner.AndAsync("Click On Course Payment Next Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
   await testRunner.AndAsync(string.Format("Enter Student Payment Amount \"{0}\"", paymentAmount), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
   await testRunner.AndAsync(string.Format("Select Student Payment Method \"{0}\"", paymentMethod), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
   await testRunner.AndAsync("Click On ProceedToPay Button With Terms&Condition", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
   await testRunner.AndAsync("Click On Ssl Commerz Payment Success Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
  await testRunner.ThenAsync("Is Success Student Program Course Enrollment", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await StudentProgramEnrolmentFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await StudentProgramEnrolmentFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
