// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UMS.UI.Test.ERP.Areas.Administration.Bank
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ManageBankFeature : object, Xunit.IClassFixture<ManageBankFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Areas/Administration/Bank", "Manage Bank", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ManageBank.feature"
#line hidden
        
        public ManageBankFeature(ManageBankFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="T1 Create Bank Test")]
        [Xunit.TraitAttribute("FeatureTitle", "Manage Bank")]
        [Xunit.TraitAttribute("Description", "T1 Create Bank Test")]
        [Xunit.TraitAttribute("Category", "CreateBank")]
        [Xunit.TraitAttribute("Category", "DataSource:../../../TestData/Administration/Excel/Bank.xlsx")]
        [Xunit.TraitAttribute("Category", "DataSet:ManageBank")]
        [Xunit.InlineDataAttribute("1", "SQA Bank", "SQAB", "Kawran Bazar, Dhaka - 1215", new string[0])]
        public async System.Threading.Tasks.Task T1CreateBankTest(string sL, string fullName, string shortName, string address, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CreateBank",
                    "DataSource:../../../TestData/Administration/Excel/Bank.xlsx",
                    "DataSet:ManageBank"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("SL", sL);
            argumentsOfScenario.Add("FullName", fullName);
            argumentsOfScenario.Add("ShortName", shortName);
            argumentsOfScenario.Add("Address", address);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("T1 Create Bank Test", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("Goto Manage Bank Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
  await testRunner.WhenAsync("Click On Add Bank Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
  await testRunner.ThenAsync("Is Show Desired Test Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 10
  await testRunner.WhenAsync(string.Format("Enter Bank Full Name \"{0}\"", fullName), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
   await testRunner.AndAsync(string.Format("Enter Bank Short Name \"{0}\"", shortName), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
   await testRunner.AndAsync(string.Format("Enter Bank Address \"{0}\"", address), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
   await testRunner.AndAsync("Click On Bank Create Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
  await testRunner.ThenAsync("Is Show Action Success Message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="T2 Update Bank Test")]
        [Xunit.TraitAttribute("FeatureTitle", "Manage Bank")]
        [Xunit.TraitAttribute("Description", "T2 Update Bank Test")]
        [Xunit.TraitAttribute("Category", "UpdateBank")]
        [Xunit.TraitAttribute("Category", "DataSource:../../../TestData/Administration/Excel/Bank.xlsx")]
        [Xunit.TraitAttribute("Category", "DataSet:ManageBank")]
        [Xunit.InlineDataAttribute("1", "SQA Bank", "SQAB", "Kawran Bazar, Dhaka - 1215", new string[0])]
        public async System.Threading.Tasks.Task T2UpdateBankTest(string sL, string fullName, string shortName, string address, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "UpdateBank",
                    "DataSource:../../../TestData/Administration/Excel/Bank.xlsx",
                    "DataSet:ManageBank"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("SL", sL);
            argumentsOfScenario.Add("FullName", fullName);
            argumentsOfScenario.Add("ShortName", shortName);
            argumentsOfScenario.Add("Address", address);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("T2 Update Bank Test", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
 await testRunner.GivenAsync("Goto Manage Bank Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
  await testRunner.WhenAsync(string.Format("Enter Bank Full Name \"{0}\"", fullName), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
   await testRunner.AndAsync("Click On Bank Search Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
   await testRunner.AndAsync("Click On Update Glyph Icon", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
  await testRunner.ThenAsync("Is Show Desired Test Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 25
  await testRunner.WhenAsync(string.Format("Enter Bank Full Name \"{0} v2\"", fullName), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
   await testRunner.AndAsync(string.Format("Enter Bank Short Name \"{0} v2\"", shortName), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
   await testRunner.AndAsync(string.Format("Enter Bank Address \"{0} v2\"", address), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
   await testRunner.AndAsync("Click On Bank Update Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
  await testRunner.ThenAsync("Is Show Action Success Message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="T3 Delete Bank Test")]
        [Xunit.TraitAttribute("FeatureTitle", "Manage Bank")]
        [Xunit.TraitAttribute("Description", "T3 Delete Bank Test")]
        [Xunit.TraitAttribute("Category", "DeleteBank")]
        [Xunit.TraitAttribute("Category", "DataSource:../../../TestData/Administration/Excel/Bank.xlsx")]
        [Xunit.TraitAttribute("Category", "DataSet:ManageBank")]
        [Xunit.InlineDataAttribute("1", "SQA Bank", "SQAB", "Kawran Bazar, Dhaka - 1215", new string[0])]
        public async System.Threading.Tasks.Task T3DeleteBankTest(string sL, string fullName, string shortName, string address, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DeleteBank",
                    "DataSource:../../../TestData/Administration/Excel/Bank.xlsx",
                    "DataSet:ManageBank"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("SL", sL);
            argumentsOfScenario.Add("FullName", fullName);
            argumentsOfScenario.Add("ShortName", shortName);
            argumentsOfScenario.Add("Address", address);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("T3 Delete Bank Test", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
   await testRunner.GivenAsync("Goto Manage Bank Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
 await testRunner.WhenAsync(string.Format("Enter Bank Short Name \"{0} v2\"", shortName), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
  await testRunner.AndAsync("Click On Bank Search Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
  await testRunner.AndAsync("Click On Delete Glyph Icon", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
  await testRunner.AndAsync("Click On Modal Danger Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
 await testRunner.ThenAsync("Is Show Action Success Message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ManageBankFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ManageBankFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
